### ISSUE TITLE
if month is not numeric

### ISSUE THREAD

**Issue by dicook** [maliny12/sugarglider#11]
It might be worthwhile to handle factor versions of the x_major variable. Currently if month is coded as J, F, .... the code errors

**Comment by maliny12** [comment]
If the user has a factor variable with appropriate levels, they can convert it to numeric prior to passing the argument to the plotting function.

```
aus_temp |>
  mutate(month_fct = factor(case_when(month == 1 ~ "Jan",
                                      month == 2 ~ "Feb",
                                      month == 3 ~ "Mar",
                                      month == 4 ~ "Apr",
                                      month == 5 ~ "May",
                                      month == 6 ~ "Jun",
                                      month == 7 ~ "Jul",
                                      month == 8 ~ "Aug",
                                      month == 9 ~ "Sep",
                                      month == 10 ~ "Oct",
                                      month == 11 ~ "Nov",
                                      month == 12 ~ "Dec"),
                            levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))) |> 
  ggplot(aes(x_major = long, y_major = lat,
             x_minor = as.numeric(month_fct), ymin_minor = tmin, ymax_minor = tmax)) +
  geom_glyph_ribbon()

```

I could modify the function to handle factor variables directly, but this would require me to hardcode the group argument and force them to be identical. For some reason, factors generate multiple groupings, which disrupts the plotting.

![Screenshot 2024-09-29 at 10 49 08 PM](https://github.com/user-attachments/assets/69dff123-bd7c-4d8b-91a4-b755f5f6d8d4)


What are your thoughts on this?

**Comment by dicook** [comment]
At a minimum, catching the error is a good start. So check the type of variable and if a factor then issue an error with a message. Or just a warning, if the code will work once you've made a fix. 

Beyond this, I'm not sure why you would need to to hard code the group variable. Doing an as.numeric() on a factor should generate reasonable set of integers.
